In [ ]:
import os
import sys
import glob
import pickle
import shutil
import zipfile

import numpy as np
import matplotlib.pyplot as plt

### FILES ###
import shutil # delate directory
import zipfile # extract a directory

In [ ]:
# ELIMINARE UNA CARTELLA DA CONTENT

folder = "/content/Dataset"

if os.path.exists(folder):
    shutil.rmtree(folder)
    print("Delated directory")
else:
    print("No delated directory")

No delated directory


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

LOCAL_ROOT = "/content/Dataset"

def unzip_file(zip_path):

    os.makedirs(LOCAL_ROOT, exist_ok=True)

    zip_name = os.path.basename(zip_path)

    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(LOCAL_ROOT)

    print(f"{zip_name} has extracted.")

unzip_file("/content/drive/MyDrive/DATASET_SHARP/Python_code_old.zip")
unzip_file("/content/drive/MyDrive/DATASET_SHARP/doppler_traces.zip")
unzip_file("/content/drive/MyDrive/DATASET_SHARP/doppler_traces_S4_S5.zip")

Mounted at /content/drive
Python_code_old.zip has extracted.
doppler_traces.zip has extracted.
doppler_traces_S4_S5.zip has extracted.


In [ ]:
S1A_PATH = "/content/Dataset/doppler_traces/S1a"
actions = ["C", "E", "H", "J1", "J2", "L", "R", "S", "W"]
dataset_array = {
    "C": [],
    "E": [],
    "H": [],
    "J1": [],
    "J2": [],
    "L": [],
    "R": [],
    "S": [],
    "W": []
}

dataset_array_shape = {
    "C": [],
    "E": [],
    "H": [],
    "J1": [],
    "J2": [],
    "L": [],
    "R": [],
    "S": [],
    "W": []
}

for action in actions:

  for filename in os.listdir(S1A_PATH):
    if filename.startswith(f"S1a_{action}"):

      file_path = os.path.join(S1A_PATH, filename)

      with open(file_path, "rb") as fp:
        doppler = pickle.load(fp)

      dataset_array[action].append(doppler)

for action in actions:
    print(f"\nAzione {action}")
    dataset_array_shape[action].append(np.array((dataset_array[action])).shape)
    print(np.array(dataset_array_shape[action]))

    for i, stream in enumerate(dataset_array[action]):
        stream = np.asarray(stream)
        print(f"stream_{i}: shape = {stream.shape}, dtype = {stream.dtype}")





Azione C
[[    4 18766   100]]
stream_0: shape = (18766, 100), dtype = float64
stream_1: shape = (18766, 100), dtype = float64
stream_2: shape = (18766, 100), dtype = float64
stream_3: shape = (18766, 100), dtype = float64

Azione E
[[    4 18700   100]]
stream_0: shape = (18700, 100), dtype = float64
stream_1: shape = (18700, 100), dtype = float64
stream_2: shape = (18700, 100), dtype = float64
stream_3: shape = (18700, 100), dtype = float64

Azione H
[[    4 19064   100]]
stream_0: shape = (19064, 100), dtype = float64
stream_1: shape = (19064, 100), dtype = float64
stream_2: shape = (19064, 100), dtype = float64
stream_3: shape = (19064, 100), dtype = float64

Azione J1
[[   4 8700  100]]
stream_0: shape = (8700, 100), dtype = float64
stream_1: shape = (8700, 100), dtype = float64
stream_2: shape = (8700, 100), dtype = float64
stream_3: shape = (8700, 100), dtype = float64

Azione J2
[[   4 8708  100]]
stream_0: shape = (8708, 100), dtype = float64
stream_1: shape = (8708, 100), dt

In [ ]:
# WINDOW OF 1@(340 x 100)
def create_sliding_windows(data, window_length=340, stride=1):

  data = np.array(data)
  complete_dataset = []
  # elements of each action
  num_streams, time_length, num_features = np.array(data).shape
  print(num_streams, time_length, num_features)

  for stream in range(0,num_streams):

    windows = []

    if time_length < window_length:
      window.append(data[stream])
      print("The dataset is less than window size")
      continue

    start = 0
    end = 340
    window = []
    while end <= time_length:
      window = []
      window = np.array(data[stream][start:end,:])
      windows.append(window)
      start += stride
      end += stride

    if end > time_length:
      window = np.array(data[stream][start:time_length,:])
      windows.append(window)

    complete_dataset.append(windows)

    print(f"Stream: {num_streams}, lunghezza: {time_length}, feature: {num_features}")
    print(f"Finestre stream {stream}: {windows[-1].shape}")
    print(f"Windows for stream {stream}: {len(windows)}")
    print(f"Dimension of window: {len(windows[-1])}")
    print("---------------------------------------")

  return complete_dataset

print("** SLIDING WINDOWS C **")
windowsC = create_sliding_windows(dataset_array["C"], 340, 340)
#print("Shape of windows C", windowsC.shape)
print("** SLIDING WINDOWS E **")
windowsE = create_sliding_windows(dataset_array["E"], 340, 340)
print("** SLIDING WINDOWS H **")
windowsH = create_sliding_windows(dataset_array["H"], 340, 340)
print("** SLIDING WINDOWS J1 **")
windowsJ1 = create_sliding_windows(dataset_array["J1"], 340, 340)
print("** SLIDING WINDOWS J2 **")
windowsJ2 = create_sliding_windows(dataset_array["J2"], 340, 340)
print("** SLIDING WINDOWS L **")
windowsL = create_sliding_windows(dataset_array["L"], 340, 340)
print("** SLIDING WINDOWS R **")
windowsR = create_sliding_windows(dataset_array["R"], 340, 340)
print("** SLIDING WINDOWS S **")
windowsS = create_sliding_windows(dataset_array["S"], 340, 340)
print("** SLIDING WINDOWS W **")
windowsW = create_sliding_windows(dataset_array["W"], 340, 340)


** SLIDING WINDOWS C **
4 18766 100
Stream: 4, lunghezza: 18766, feature: 100
Finestre stream 0: (66, 100)
Windows for stream 0: 56
Dimension of window: 66
---------------------------------------
Stream: 4, lunghezza: 18766, feature: 100
Finestre stream 1: (66, 100)
Windows for stream 1: 56
Dimension of window: 66
---------------------------------------
Stream: 4, lunghezza: 18766, feature: 100
Finestre stream 2: (66, 100)
Windows for stream 2: 56
Dimension of window: 66
---------------------------------------
Stream: 4, lunghezza: 18766, feature: 100
Finestre stream 3: (66, 100)
Windows for stream 3: 56
Dimension of window: 66
---------------------------------------
** SLIDING WINDOWS E **
4 18700 100
Stream: 4, lunghezza: 18700, feature: 100
Finestre stream 0: (0, 100)
Windows for stream 0: 56
Dimension of window: 0
---------------------------------------
Stream: 4, lunghezza: 18700, feature: 100
Finestre stream 1: (0, 100)
Windows for stream 1: 56
Dimension of window: 0
------------